# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/CMPE_Capstone/CODE/hdl/pkt_display/pkt_display.srcs/sources_1/bd/design_1/ip/design_1_pkt_display_wrapper_0_3/design_1_pkt_display_wrapper_0_3.xci
# IP: The module: 'design_1_pkt_display_wrapper_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/CMPE_Capstone/CODE/hdl/pkt_display/pkt_display.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/pkt_display/pkt_display.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/pkt_display/pkt_display.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: d:/CMPE_Capstone/CODE/hdl/pkt_display/pkt_display.gen/sources_1/bd/design_1/ip/design_1_pkt_display_wrapper_0_3/design_1_pkt_display_wrapper_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pkt_display_wrapper_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/pkt_display/pkt_display.srcs/sources_1/bd/design_1/ip/design_1_pkt_display_wrapper_0_3/design_1_pkt_display_wrapper_0_3.xci
# IP: The module: 'design_1_pkt_display_wrapper_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/CMPE_Capstone/CODE/hdl/pkt_display/pkt_display.srcs/sources_1/ip/blk_mem_gen_0_1/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/pkt_display/pkt_display.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/pkt_display/pkt_display.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: d:/CMPE_Capstone/CODE/hdl/pkt_display/pkt_display.gen/sources_1/bd/design_1/ip/design_1_pkt_display_wrapper_0_3/design_1_pkt_display_wrapper_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_pkt_display_wrapper_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
