# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/CMPE_Capstone/CODE/hdl/PROC/PROC_leader_test/PROC_leader_test.srcs/sources_1/bd/design_1/ip/design_1_RF_top_0_0/design_1_RF_top_0_0.xci
# IP: The module: 'design_1_RF_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/CMPE_Capstone/CODE/hdl/PROC/PROC_leader_test/PROC_leader_test.srcs/sources_1/ip/ila_0_2/ila_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/PROC/PROC_leader_test/PROC_leader_test.srcs/sources_1/ip/blk_mem_gen_0_2/blk_mem_gen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/PROC/PROC_leader_test/PROC_leader_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/PROC/PROC_leader_test/PROC_leader_test.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/PROC/PROC_leader_test/PROC_leader_test.srcs/sources_1/bd/design_1/ip/design_1_RF_top_0_0/design_1_RF_top_0_0.xci
# IP: The module: 'design_1_RF_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: D:/CMPE_Capstone/CODE/hdl/PROC/PROC_leader_test/PROC_leader_test.srcs/sources_1/ip/ila_0_2/ila_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ila_0 || ORIG_REF_NAME==ila_0} -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/PROC/PROC_leader_test/PROC_leader_test.srcs/sources_1/ip/blk_mem_gen_0_2/blk_mem_gen_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/PROC/PROC_leader_test/PROC_leader_test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: D:/CMPE_Capstone/CODE/hdl/PROC/PROC_leader_test/PROC_leader_test.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet
