# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/JohnPC/Documents/GitHub/CMPE_Capstone/CODE/hdl/PMODESP32/synth/esp_ctrl.xdc

# IP: ip/axi_uartlite_1/axi_uartlite_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_uartlite_1 || ORIG_REF_NAME==axi_uartlite_1} -quiet] -quiet
