M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu22.04.1} date Wed 07 Feb 2024 03:02:49 PM EST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-07T15:02:49-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0709
%
G90
G05
T1
X7.8Y-1.7878
X7.8Y-3.3878
X8.4Y-1.7878
X8.4Y-3.3878
M30
